name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    integration:
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [16.x]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js environment
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - name: install modules
              run: npm install
            - name: build production project
              run: npm run build:prod
            - name: linting ts
              run: npm run lint:ts
            - name: linting css
              run: npm run lint:scss
            - name: unit tests
              run: npm run test:unit
            - name: run storybook
              run: npm run storybook:build
            - name: screenshot testing
              run: npm run test:ui:ci
